### ISSUE TITLE
Less an issue than a question...

### ISSUE THREAD

**Issue by alban-eolas** [geeksville/steamback#37]
I noticed that Steamback has been packaged for NixOS though I'm wondering how it can be used as a Decky plugin when Decky itself is not made available as a Nixpkg.

Sorry for the unrelated question, but couldn't think of anywhere else to really ask.

**Comment by geeksville** [comment]
The 'backend' of decky plugins are written in python.  So when I wrote the plug-in I was slightly careful to structure things so I could use the same code in a standalone python app.  Does that help?
