### ISSUE TITLE
add option to another steam installation dir

### ISSUE THREAD

**Issue by jabuxas** [geeksville/steamback#6]
i have whole steam inside a ~/steam folder, so steam thinks HOME is $HOME/steam instead of $HOME, that makes it more clean and doesn't make the home folder bloated.

it would be nice to add an option to change steam dir location, which shouldn't be hard to do. 

plus it would probably make it compatible with flatpak if it's not already (i just checked the hardcored ~/.local/share/Steam and not if it has flatpak support)

of course those are all for pc and not for steamdeck so if it isn't the purpose of the application then I'm sorry

**Comment by geeksville** [comment]
Oh yeah shouldn't be too hard to add a --steamdir (argparse) option at the beginning of __main__.py.  Alas - I'm going out of town soon.  Hopefully someone will send in a pull-request to add that option, if not I'll add it when I get back (a few months).

**Comment by jabuxas** [comment]
I'll be trying to make a commit for that

**Comment by geeksville** [comment]
cool beans! - somewhere in this neighborhood would probably be good.  argparse documentation will have more inof: https://github.com/geeksville/steamback/blob/main/defaults/py_modules/steamback/__main__.py#L20
