### ISSUE TITLE
Snapshots for Windows games running through Proton

### ISSUE THREAD

**Issue by Schmensch** [geeksville/steamback#7]
Steam games running through Proton save all game data in a wine prefix under steamapps/compdata/game-id. It could be possible to save all their data with snapshots of those folders.

**Comment by geeksville** [comment]
Hmm.  It should find those save game files already.  Is there a particular "steam cloud" enabled game it did not find?  If so, would you mind running "steamback --debug" and capturing the log that it prints at startup and adding it to this bug?

**Comment by geeksville** [comment]
@Schmensch ?
